import { useState } from 'react'
import { recordAiAck } from '../utils/disclaimer'
import { FIELD_LABEL, INPUT, CARD, ErrorBox, PrimaryButton } from './ui'

// One-time, named, logged acknowledgment of what the AI is and isn't.
// Shown after sign-in, before the app — required before any beta user
// touches AI features in a safety context.
export default function AiDisclaimer({ defaultName, onDone }) {
  const [name, setName] = useState(defaultName || '')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  const agree = async () => {
    if (!name.trim()) { setError('Type your name to confirm you’ve read this.'); return }
    setSaving(true); setError('')
    try {
      await recordAiAck(name)
      onDone()
    } catch (e) {
      setError(e?.message || 'Could not save your confirmation — check your signal and try again.')
      setSaving(false)
    }
  }

  const point = (title, body) => (
    <div style={{ marginBottom: '0.9rem' }}>
      <div style={{ fontSize: '0.85rem', fontWeight: 800, color: 'var(--text-primary)', marginBottom: '0.15rem' }}>{title}</div>
      <p style={{ fontSize: '0.82rem', color: 'var(--text-muted)', margin: 0, lineHeight: 1.55, fontWeight: 500 }}>{body}</p>
    </div>
  )

  return (
    <div style={{ minHeight: '100vh', backgroundColor: 'var(--bg-page)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '1.5rem' }}>
      <div style={{ width: '100%', maxWidth: 430 }}>
        <div style={{ fontSize: '0.66rem', fontWeight: 800, letterSpacing: '0.3em', textTransform: 'uppercase', color: 'var(--accent-soft)', marginBottom: '0.75rem', textAlign: 'center' }}>Safe Intelligence</div>
        <h1 style={{ fontSize: '1.5rem', fontWeight: 800, margin: '0 0 0.4rem', textAlign: 'center', color: 'var(--text-primary)' }}>Before you start</h1>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', margin: '0 0 1.25rem', textAlign: 'center', fontWeight: 600 }}>
          One thing you need to understand about the AI in this app.
        </p>

        <div style={{ ...CARD, marginBottom: '1rem' }}>
          {point('AI can be wrong.', 'Gaz and the AI-written reports are generated by artificial intelligence. They can be incomplete, out of date, or simply wrong — and sound confident while being wrong.')}
          {point('It’s not professional or legal advice.', 'Nothing the AI produces replaces WHS law, your site’s documented procedures, or your own professional judgement.')}
          {point('Check before you act.', 'Read and verify every AI answer and report before you rely on it, act on it, or send it to anyone.')}
          {point('You stay responsible.', 'Whatever you submit, sign or act on is your call. The AI is an assistant — not an authority.')}
        </div>

        <div style={{ marginBottom: '0.75rem' }}>
          <div style={FIELD_LABEL}>Type your name to confirm</div>
          <input value={name} onChange={e => setName(e.target.value)} placeholder="Your full name" autoComplete="name" style={INPUT} />
        </div>

        <ErrorBox style={{ marginBottom: '0.75rem' }}>{error}</ErrorBox>

        <PrimaryButton onClick={agree} disabled={!name.trim()} loading={saving}>
          {saving ? 'Saving…' : 'I’ve read this and I understand'}
        </PrimaryButton>

        <p style={{ fontSize: '0.68rem', color: 'var(--text-faint)', textAlign: 'center', marginTop: '0.75rem', fontWeight: 600 }}>
          Your confirmation is recorded with your name and the date.
        </p>
      </div>
    </div>
  )
}
