// Build a clean, presentable PDF of a report (text + photos inline) and push it
// straight through the native share sheet (email / WhatsApp / Files). Falls back
// to a download on desktop. Photos are interspersed with the content, not dumped
// at the end, so it reads like a proper report you'd hand a client.
import { jsPDF } from 'jspdf'

const ACCENT = [47, 111, 228]   // brand blue (#2f6fe4) — reads well on white
const DARK = [22, 24, 28]
const GREY = [101, 105, 111]
const LINE = [221, 217, 211]

const imgFormat = (dataUrl) => {
  if (/^data:image\/png/i.test(dataUrl)) return 'PNG'
  if (/^data:image\/webp/i.test(dataUrl)) return 'WEBP'
  return 'JPEG'
}

export async function exportReportPdf({ filename = 'report.pdf', title = 'Report', dateLabel = '', advisor = '', blocks = [] }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const M = 48
  const CW = pageW - M * 2
  let y = M

  const ensure = (h) => { if (y + h > pageH - M - 16) { doc.addPage(); y = M } }
  const para = (text, size, color, font = 'normal', lineH = 15) => {
    doc.setFont('helvetica', font); doc.setFontSize(size); doc.setTextColor(...color)
    for (const ln of doc.splitTextToSize(String(text), CW)) { ensure(lineH); doc.text(ln, M, y); y += lineH }
  }

  // --- Header ---
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(...ACCENT)
  doc.text('SAFE INTELLIGENCE', M, y); y += 20
  doc.setFont('helvetica', 'bold'); doc.setFontSize(20); doc.setTextColor(...DARK)
  doc.text(title, M, y); y += 16
  const meta = [dateLabel, advisor].filter(Boolean).join('   ·   ')
  if (meta) { doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...GREY); doc.text(meta, M, y); y += 6 }
  y += 10
  doc.setDrawColor(...LINE); doc.setLineWidth(1); doc.line(M, y, pageW - M, y); y += 20

  // --- Body blocks ---
  for (const block of blocks) {
    if (block.type === 'meta') {
      for (const row of block.rows || []) {
        if (!row.value) continue
        para(String(row.label).toUpperCase(), 8.5, GREY, 'bold', 12)
        para(row.value, 11, DARK, 'normal', 15)
        y += 6
      }
      y += 4
    } else if (block.type === 'section') {
      if (!block.body) continue
      ensure(20); para(block.heading || '', 12, ACCENT, 'bold', 16)
      para(block.body, 11, DARK, 'normal', 15)
      y += 12
    } else if (block.type === 'photos') {
      const photos = (block.photos || []).filter(Boolean)
      if (!photos.length) continue
      ensure(20); para(block.heading || 'Photos', 12, ACCENT, 'bold', 16)
      for (const p of photos) {
        let w = Math.min(CW, 430), h = w * 0.66
        try {
          const props = doc.getImageProperties(p)
          const ratio = props.height / props.width
          h = w * ratio
          const maxH = pageH - M * 2 - 20
          if (h > maxH) { h = maxH; w = h / ratio }
        } catch (_) { /* use default box */ }
        ensure(h + 12)
        try { doc.addImage(p, imgFormat(p), M, y, w, h) } catch (_) { /* skip bad image */ }
        y += h + 12
      }
      y += 4
    }
  }

  // --- Footer on every page ---
  const total = doc.getNumberOfPages()
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...GREY)
    doc.text('Generated by Safe Intelligence', M, pageH - 24)
    doc.text(`Page ${i} of ${total}`, pageW - M, pageH - 24, { align: 'right' })
  }

  // --- Share, or download as fallback ---
  const blob = doc.output('blob')
  const file = new File([blob], filename, { type: 'application/pdf' })
  try {
    if (navigator.canShare && navigator.canShare({ files: [file] })) {
      await navigator.share({ files: [file], title })
      return 'shared'
    }
  } catch (e) {
    if (e && e.name === 'AbortError') return 'cancelled'
    // fall through to download
  }
  try {
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = filename
    document.body.appendChild(a); a.click(); document.body.removeChild(a)
    setTimeout(() => URL.revokeObjectURL(url), 1500)
    return 'downloaded'
  } catch (_) { return 'failed' }
}
