import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)

// Offline support: register the Workbox service worker (generated by
// vite-plugin-pwa). 'autoUpdate' mode means a new deploy installs in the
// background, takes control immediately, and reloads the page — no stale
// builds (the failure mode that got the old hand-written SW removed).
import { registerSW } from 'virtual:pwa-register'
registerSW({ immediate: true })
